nelmio_cors:
    defaults:
        allow_origin: ['^https?://(localhost|127\.0\.0\.1|180\.149\.199\.210)(:[0-9]+)?$']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Set-Cookie']
        max_age: 3600
        origin_regex: true
    paths:
        '^/': ~